project:
  type: website
  output-dir: _site
  preview:
    port: 5896
    browser: true
  render:
    - "*.qmd"
    - "modules/*.qmd"
    - "!fragments/*"
  resources:
    - "data/"
    - "slides/"
    - "images/"

website:
  title: Intro to Population Data Science
  description: 'Course website for the PRC course "Intro to Population Data Science" at Portland State University'
  repo-url: https://github.com/nsacco/pop-data-science
  repo-actions: [edit, issue]
  search: true
  sidebar:
    style: "docked"
    collapse-level: 1
    search: true
    contents:
      - text: "üè† Home"
        href: index.qmd
      - text: "üó∫Ô∏è Syllabus"
        href: modules/0.0-syllabus.qmd
      - section: "üìä Modules"
        contents:
          - text: "Module 1: Introduction"
            href: modules/1.0-intro.qmd
          - text: "Module 2: Data Sources"
            href: modules/2.0-data-sources.qmd
          - text: "Module 3: Data Cleaning"
            href: modules/3.0-cleaning.qmd
          - text: "Module 4: Visualization"
            href: modules/4.0-visualization.qmd
          - text: "Module 5: Models"
            href: modules/5.0-models.qmd
          - text: "Module 6: Final Project"
            href: modules/6.0-project.qmd
      - section: "üéûÔ∏è Slides"
        contents:
          - text: "Lecture 1 ‚Äì Intro"
            href: slides/01-intro-slides.qmd
          - text: "Lecture 2 ‚Äì Data Sources"
            href: slides/02-data-sources-slides.qmd
          - text: "Lecture 3 ‚Äì Data Cleaning"
            href: slides/03-cleaning-slides.qmd
          - text: "Lecture 4 ‚Äì Visualization"
            href: slides/04-visualization-slides.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    toc-location: right
    number-sections: true
    link-external-newwindow: true
    anchor-sections: true
    smooth-scroll: true
    css: styles.css
